### ISSUE TITLE
Add GDA support to SDK-Core

### ISSUE THREAD

**Issue by philipandersson** [superfluid-finance/protocol-monorepo#1485] opened 2023-07-04 08:08 UTC

**Comment by philipandersson** [comment] 2023-07-04 08:09
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Protocol-Team-6405e4d5014c0d0036e14f49/issues/superfluid-finance/protocol-monorepo/1485?planning-poker) with Zenhub @0xdavinchee @hellwolf @d10r @ngmachado

**Comment by vmichalik** [comment] 2023-07-10 08:04
Duplicate of #263

**Closed as not planned by vmichalik** 2023-07-10 08:04 UTC
Labels: Project: SDK-CORE, Team: Protocol
