### ISSUE TITLE
[SUPPORT] Debug SuperApp App Credit issue (closing incoming stream reverts)

### ISSUE THREAD

**Issue by d10r** [superfluid-finance/protocol-monorepo#1736] opened 2023-10-24 15:24 UTC
Tracking in an issue as it may give valuable insights to ourselves.

https://discord.com/channels/752490247643725875/752493348169711696/1165125913495752794

https://github.dev/markcarey/stream2own/blob/gooddollar/contracts/S2OSuperApp.sol#L182

scenario:

TX1:
* A streams to SuperApp with flowrate 100e16
* SuperApp splits stream of A into 5e16 to X and 95e16 to Y

TX2:
* B streams to SuperApp with flowrate 300e16
* SuperApp deletes stream of A
* SuperApp splits stream of B into 7.5e16 to A, 7.5e16 to X and 275e16 to Y

TX2 has an unexpected revert with `APP_RULE_NO_CRITICAL_RECEIVER_ACCOUNT`

**Comment by 0xdavinchee** [comment] 2023-10-24 16:57
There are some wider issues/confusions regarding deposit clipping as well as the way that app credit works when it comes to SuperApp development.

An ideal output for this issue is some sort of framework, diagrams or whatever it is which makes understanding and developing super apps and dealing with app credit more feasible.

This will not only benefit Mark Carey, but it will also aid us down the line.

**Comment by d10r** [comment] 2023-10-25 11:24
After suspecting clipping issues (rounding artifact or min deposit), it seems to just be a bad ordering.
Mark was assuming that the invariant `netFlowRate >= 0` for the SuperApp has to be true at the end of the tx, not during the tx too.

Also not.

> Not sure if this helps, but I kept gradually increasing the contract "preDeposit" until the revert stopped. Once I increased it from 1e12 to 1e22 it finally stopped reverting.  Then I had a hunch that perhaps the amount needed to be equal to the 1 hour deposit as shown at https://console.superfluid.finance/polygon-zkevm-testnet/protocol. Note that the initial stream was 1 token per second (1e18) and so a one hour deposit would be 3,600 tokens (3.6e21).  When I set the preDeposit to 3600 it reverts but setting it to 3700 it succeeds. Perhaps this number shouldn't be surprising, but it doesn't explain why the contract would need hold a deposit after the stream is deleted, while the total outflows are exactly equal to the remaining inflow stream. 

> It is almost as if the deleteFlow() call incurred its own accounting calculation, without consideration for the inflow from B and the updated outflows that are happening within the same callback. In this isolated scenario (ignoring inflow B and the changed outflows it triggers), you start with 1e18 infFlow and 1e18 outFlow. If you then delete the inFlow but not the outflow, then the contract would need to hold a 1 hour deposit itself.  .... is this a recursion/re-entrance issue?

**Comment by d10r** [comment] 2023-10-26 15:50
minimized test case:
https://github.com/d10r/sf-appcredit-test

intermediate conclusion: the use case Mark wants isn't supported by the current implementation.

The goal now is to understand what exactly the limitations are and making sure it's just a limitation, not a bug.
Nuno wants to keep digging later.

raw output of a test run:
```
$ forge test -vv
[⠆] Compiling...
[⠘] Compiling 2 files with 0.8.19
[⠊] Solc 0.8.19 finished in 7.47s
Compiler run successful!

Running 1 test for test/SuperApp.t.sol:SuperAppTest
[FAIL. Reason: APP_RULE(12)] testMarkScenario() (gas: 2623780)
Logs:
  
====== Getting First Stream
  
  === tx1 initial state
  ctx app credit granted 14400000000005486149632
  ctx app credit used:
  0
  ctx app credit remaining:
  14400000000005486149632
  app netflowrate 1000000000000000000
  app balance:  0
  app availableBalance:
  0
  app deposit 0
  app owedDeposit 0
  remaining max flowrate from deposit:
  1000000000000380982
  
  ====== after creating outflow
  ctx app credit granted 14400000000005486149632
  ctx app credit used:
  14400000000001191182336
  ctx app credit remaining:
  4294967296
  app netflowrate 0
  app balance:  0
  app availableBalance:
  -14400000000001191182336
  app deposit 14400000000001191182336
  app owedDeposit 0
  remaining max flowrate from deposit:
  298261
  
====== Getting Second Stream
  
  === tx2 initial state
  ctx app credit granted 28800000000006677331968
  ctx app credit used:
  0
  ctx app credit remaining:
  28800000000006677331968
  app netflowrate 2000000000000000000
  app balance:  0
  app availableBalance:
  0
  app deposit 14400000000001191182336
  app owedDeposit 14400000000001191182336
  remaining max flowrate from deposit:
  2000000000000463703
  
  === after updating outflow
  ctx app credit granted 28800000000006677331968
  ctx app credit used:
  14400000000001191182336
  ctx app credit remaining:
  14400000000005486149632
  app netflowrate 1000000000000000000
  app balance:  0
  app availableBalance:
  -14400000000001191182336
  app deposit 28800000000002382364672
  app owedDeposit 14400000000001191182336
  remaining max flowrate from deposit:
  1000000000000380982
  
  === after deleting first inflow
  ctx app credit granted 28800000000006677331968
  ctx app credit used:
  0
  ctx app credit remaining:
  28800000000006677331968
  app netflowrate 0
  app balance:  0
  app availableBalance:
  -14400000000001191182336
  app deposit 28800000000002382364672
  app owedDeposit 0
  remaining max flowrate from deposit:
  2000000000000463703

Test result: FAILED. 0 passed; 1 failed; 0 skipped; finished in 19.18ms
 
Ran 1 test suites: 0 tests passed, 1 failed, 0 skipped (1 total tests)

Failing tests:
Encountered 1 failing test in test/SuperApp.t.sol:SuperAppTest
[FAIL. Reason: APP_RULE(12)] testMarkScenario() (gas: 2623780)

Encountered a total of 1 failing tests, 0 tests succeeded
```

@ngmachado helping out

**Comment by markcarey** [comment] 2023-10-29 12:44
Please let me know if I can help with any additional info. From what I can tell, the minimal test case contract looks like a cleaner way to reproduce/demonstrate the issue. It seems to show that it is not a 1:N issue, since the test reverts in a 1:1 scenario as well...

**Comment by d10r** [comment] 2023-10-31 08:30
y exactly @markcarey , the splitting seems to not be important here, just the deleting of an incoming flow.

**Comment by markcarey** [comment] 2023-11-02 17:53
Just to add a data point that seems relevant, even though it does **not** involve closing an incoming stream from a Super App.

The version I submitted for the Wave Pool includes some pre-funding of the Super App.  Here is a scenario:

- sender starts with a balance of `10 G$`, super app starts with `0 G$`
- the sender transfers `1 G$` to super app (1e18)
- the sender starts a stream of `1 G$ per day` (flowRate == 11574074074074)
- the sender's balance is now reported as `~6.8 G$`, super app balance == `0.1666 G$`, contract netFlow == `0`

From user perspective, it would be logical to assume that the balance after starting the stream would be _almost_ `9 G$` -- and not _less than 7_.  A four-hour deposit should be `0.1666 G$`. So you'd expect the balance to `8.833 G$`. Instead, the reported balance is a full `2 G$` (2e18) _lower_ than expected.

**Comment by d10r** [comment] 2023-11-02 22:49
@markcarey this can be explained by the 1e18 min deposit set for G$, see https://console.superfluid.finance/celo/supertokens/0x62b8b11039fcfe5ab0c56e502b1c372a3d2a9c7a?tab=streams
That deducts 1 for deposit and another 1 for app credit. Not sure why there's 0.2 more missing though.
Can you link to the code?

As for the other scenario: we discussed that again today. The behaviour was changed in https://github.com/superfluid-finance/protocol-monorepo/pull/945 - apparently would have worked before, but we believe that wasn't correct behaviour.
We'll dig some more, but the dominant assumption still is that this case won't work with the way AppCredit works.

What you just described - the stream sender making an explicit upfront transfer - is indeed the workaround I would suggest.
Is that something you could do here too?

**Comment by markcarey** [comment] 2023-11-03 13:50
The` /api/join` endpoint is where the above tx sequence happens:
https://github.com/markcarey/stream2own/blob/main/100good/functions/good/index.js#L525

I did not realize there was a token-specific minimum deposit. When I have created native super tokens, it seems they did not have a (or defaulted to zero) minimum deposit.

As for the behaviour change, the timing makes sense. I had has Super App projects that were "netFlow == 0" prior to that point and never ran into any issue.

The [wiki on app credit](https://github.com/superfluid-finance/protocol-monorepo/wiki/About-App-Credit) states `It is guaranteed that forwarding the same flow rate as the input stream as a zero-balance app should always work.` With #945 has this guarantee been withdrawn?

**Comment by d10r** [comment] 2023-11-06 10:17
> The [wiki on app credit](https://github.com/superfluid-finance/protocol-monorepo/wiki/About-App-Credit) states It is guaranteed that forwarding the same flow rate as the input stream as a zero-balance app should always work. With https://github.com/superfluid-finance/protocol-monorepo/pull/945 has this guarantee been withdrawn?

no, that shouldn't have changed this guarantee

**Closed as completed** 2023-11-15 09:44 UTC
Labels: Team: Protocol

**Comment by markcarey** [comment] 2023-11-15 15:18
So has this issue been fixed? I see that this has been closed and a test case added -- but I am a little confused. Has the cause of this issue been identified?

**Comment by d10r** [comment] 2023-11-15 16:39
The test case was about making sure that the accounting invariants hold in this special case.
As for the issue of reverting transactions: the status is still as described in a previous comment: we believe that this is a fundamental limitation of the AppCredit system which likely can't be fixed without significant protocol changes.
Caveat: @hellwolf wanted to also look into it. He has the most detailed understanding of this mechanism and maybe can add helpful context.

**Comment by hellwolf** [comment] 2023-11-15 16:40
@markcarey do you need help to come up with some sort of workaround to bypass this issue for you?

**Comment by markcarey** [comment] 2023-11-15 23:50
@hellwolf I tried several workarounds and the only one that seemed to work is to pre-fund the Super App beforehand. In my use case I am potentially deploying hundreds of Super Apps via a Factory contract. While this workaround could technically work in a production scenario, it might not be financially feasible for users -- I need to think more on that aspect.
